name: golangci-lint
on:
  pull_request:
    branches:
      - master
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build deps
        run: go mod vendor

      - name: Lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

          golangci-lint run